# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Implementation of Viterbi Algorithm on a Symmetric Continuous-time Markov Chain HMM using Rcpp
#'
#' Function that implements a Viterbi algorithm, given likelihood of observed data,timestamp of each observation and a parameter theta.
#'
#' @param ts size m Numeric vector containing the timestamp of each observation
#' @param theta double type value which represents the parameter theta in the model of transition probability
#' @param obs n x m Numeric matrix containing the likelihood of the observed data
#'
#' @return the Viterbi path(path)
#'
#' @examples
#' obs <- matrix(c(0.88,0.10,0.88,0.10,0.02,0.30,0.02,0.30,0.10,0.60),2,5)
#' theta <- log(2)
#' ts <- c(1,2,3,4,5)
#' ctmcViterbi(ts,theta,obs)
#' @export
ctmcViterbi <- function(ts, theta, obs) {
    .Call(`_gspyrouHW4_ctmcViterbi`, ts, theta, obs)
}

#' Implementation of ForwardBackward Algorithm on a Symmetric Continuous-time Markov Chain HMM
#'
#' Implementing the ForwardBackward algorithm,given likelihood of observed data,timestamp of each observation and a parameter theta.
#'
#' @param ts size m Numeric vector containing the timestamp of each observation
#' @param theta double type value which represents the parameter theta in the model of transition probability
#' @param obs n x m Numeric matrix containing the likelihood of the observed data
#'
#' @return a n x m matrix containing the conditional probabilities of each observation
#'
#' @examples
#' obs <- matrix(c(0.88,0.10,0.88,0.10,0.02,0.30,0.02,0.30,0.10,0.60),2,5)
#' theta <- log(2)
#' ts <- c(1,2,3,4,5)
#' ctmcForwardBackward(ts,theta,obs)
#' @export
ctmcForwardBackward <- function(ts, theta, obs) {
    .Call(`_gspyrouHW4_ctmcForwardBackward`, ts, theta, obs)
}

